version: '3.4'

services:
  diginteligencia:
    image: ${DOCKER_REGISTRY}diginteligencia
    build:
      context: .
      dockerfile: DigInteligencia/Dockerfile
    links:
      - database
    environment:
      MYSQL_SERVER_NAME: database
  database:
    image: mysql/mysql-server:5.7
    container_name: database.dev
    command: mysqld --user=root --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dbcreation.sql:/tmp/dbcreation.sql
      - ./import.sh:/tmp/import.sh
    ports:
      - "12345:3306"
    environment:
      MYSQL_DATABASE: "webapi"
      MYSQL_USER: "urivape"
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"