// <auto-generated />
using DigInteligencia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigInteligencia.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DigInteligencia.Models.TaskToDo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("TaskToDoListID");

                    b.HasKey("ID");

                    b.HasIndex("TaskToDoListID");

                    b.ToTable("TaskToDo");
                });

            modelBuilder.Entity("DigInteligencia.Models.TaskToDoList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("TaskToDoList");
                });

            modelBuilder.Entity("DigInteligencia.Models.TaskToDo", b =>
                {
                    b.HasOne("DigInteligencia.Models.TaskToDoList", "TaskToDoList")
                        .WithMany("TaskToDo")
                        .HasForeignKey("TaskToDoListID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
