version: '3.4'

services:
  diginteligencia:
    image: diginteligencia:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_diginteligencia$
    volumes:
      - C:\Users\urivape\source\repos\DigInteligencia\DigInteligencia:/app
      - C:\Users\urivape\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_diginteligencia$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_diginteligencia$ bin/Debug/netcoreapp2.1/DigInteligencia.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
